### ISSUE TITLE
Switch from deprecated gRPC methods

### ISSUE THREAD

**Issue by isinyaaa** [kubeflow/model-registry#194]
MR server uses [`grpc.DialContext`](https://pkg.go.dev/google.golang.org/grpc#DialContext) to test connections at launch time. This method has been deprecated along with timeout functionality as laid out on [gRPC anti-patterns](https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md).

There are no plans for upstream to actually deprecate those methods, but testing at connection at initialization has been recommended against as it's not guaranteed that the connection will be maintained. It's also not the standard API across other gRPC implementations.

**Comment by tarilabs** [comment]
> but testing at connection at initialization has been recommended against as it's not guaranteed that the connection will be maintained

This is considering gRPC in the frame, and I can understand that pov.

However since Model Registry is meant to be a cloud-native service, we would need to make sure the service can eventually start if the DB or the gRPC container lags in coming available.
Here could be a good thing to test scenario in KinD, once the behaviour as containerised is assessed:

1. Deploy the MR without the gRPC container or without the DB intentionally
2. wait 60 seconds
3. Deploy the gRPC container or the DB intentionally
4. make sure MR service becomes available

wdyt ?
